# Generated by Django 5.0 on 2023-12-30 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
