# Generated by Django 5.0 on 2023-12-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
