# Generated by Django 5.0 on 2023-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Topic')),
                ('description', models.CharField(max_length=350, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('supports', models.IntegerField(verbose_name='Supports')),
            ],
            options={
                'verbose_name': 'Support',
            },
        ),
    ]
