# Generated by Django 5.0 on 2023-12-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_support_user_id_support_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='supports',
        ),
    ]
