# Generated by Django 5.0 on 2023-12-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusermodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
