# Generated by Django 5.0 on 2023-12-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusermodel', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='iscompleted'),
        ),
    ]
